title: Intro to VVVV, Easily Design Interactive Installations.
baseurl: http://opentechschool-brussels.github.io/interactive-installations-with-VVVV


markdown: redcarpet
redcarpet:
   extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "strikethrough", "autolink"]

pygments: true

permalink: title.html
